### PR TITLE
update istio access log format for +1.9 proxies

### PR DESCRIPTION
**Pull request by GregHanson**
Default log format was updated in Istio 1.9 (PR https://github.com/istio/istio/pull/27903) to add `%RESPONSE_CODE_DETAIL%` and `%CONNECTION_TERMINATION_DETAILS%`

Samples Istio access logs for these fields set: 
```
[2020-10-29T03:22:16.126Z] "GET /headers HTTP/1.1" 200 - via_upstream - "-" 0 547 5 4 "-" "curl/7.73.0-DEV" "24e58e43-e576-9048-829b-02e3f3da16f0" "httpbin:8000" "127.0.0.1:80" inbound|8000|| 127.0.0.1:51680 172.17.0.7:80 172.17.0.6:59022 outbound_.8000_._.httpbin.foo.svc.cluster.local default
{
  "authority": "httpbin:8000",
  "bytes_received": "0",
  "bytes_sent": "547",
  "connection_termination_details": "-",
  "duration": "5",
  "forwarded_for": "-",
  "method": "GET",
  "protocol": "HTTP/1.1",
  "request_id": "24e58e43-e576-9048-829b-02e3f3da16f0",
  "response_flags": "-",
  "status_code": "200",
  "timestamp": "2020-10-29T03:22:16.126Z",
  "upstream_service": "127.0.0.1:80",
  "upstream_service_time": "4",
  "upstream_cluster": "inbound|8000||",
  "upstream_local": "127.0.0.1:51680",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:59022",
  "requested_server": "outbound_.8000_._.httpbin.foo.svc.cluster.local",
  "response_code_details": "via_upstream",
  "route_name": "default",
  "upstream_failure_reason": "-",
  "uri_path": "/headers",
  "user_agent": "curl/7.73.0-DEV",
  "original_message": "[2020-10-29T03:22:16.126Z] \"GET /headers HTTP/1.1\" 200 - via_upstream - \"-\" 0 547 5 4 \"-\" \"curl/7.73.0-DEV\" \"24e58e43-e576-9048-829b-02e3f3da16f0\" \"httpbin:8000\" \"127.0.0.1:80\" inbound|8000|| 127.0.0.1:51680 172.17.0.7:80 172.17.0.6:59022 outbound_.8000_._.httpbin.foo.svc.cluster.local default"
}

[2020-10-29T03:23:33.415Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 172.17.0.7:80 172.17.0.6:59800 - -
{
  "authority": "-",
  "bytes_received": "0",
  "bytes_sent": "0",
  "connection_termination_details": "-",
  "duration": "0",
  "forwarded_for": "-",
  "method": "-",
  "protocol": "-",
  "request_id": "-",
  "response_flags": "NR",
  "status_code": "0",
  "tcp_service_time": "-",
  "timestamp": "2020-10-29T03:23:33.415Z",
  "upstream_service": "-",
  "upstream_cluster": "-",
  "upstream_local": "-",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:59800",
  "requested_server": "-",
  "response_code_details": "filter_chain_not_found",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "user_agent": "-",
  "original_message": "[2020-10-29T03:23:33.415Z] \"- - -\" 0 NR filter_chain_not_found - \"-\" 0 0 0 - \"-\" \"-\" \"-\" \"-\" \"-\" - - 172.17.0.7:80 172.17.0.6:59800 - -"
}

[2020-10-29T03:24:13.520Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 172.17.0.7:80 172.17.0.6:60214 - -
{
  "authority": "-",
  "bytes_received": "0",
  "bytes_sent": "11",
  "connection_termination_details": "-",
  "duration": "0",
  "forwarded_for": "-",
  "method": "-",
  "protocol": "HTTP/1.1",
  "request_id": "-",
  "response_flags": "DPE",
  "status_code": "400",
  "tcp_service_time": "-",
  "timestamp": "2020-10-29T03:24:13.520Z",
  "upstream_service": "-",
  "upstream_cluster": "-",
  "upstream_local": "-",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:60214",
  "requested_server": "-",
  "response_code_details": "http1.codec_error",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "user_agent": "-",
  "original_message": "[2020-10-29T03:24:13.520Z] \"- - HTTP/1.1\" 400 DPE http1.codec_error - \"-\" 0 11 0 - \"-\" \"-\" \"-\" \"-\" \"-\" - - 172.17.0.7:80 172.17.0.6:60214 - -"
}

[2020-10-29T03:25:20.162Z] "GET /headers HTTP/1.1" 403 - rbac_access_denied_matched_policy[none] - "-" 0 19 0 - "-" "curl/7.73.0-DEV" "07541777-6ee2-908f-a78b-867fe257ac80" "httpbin:8000" "-" - - 172.17.0.7:80 172.17.0.6:60898 outbound_.8000_._.httpbin.foo.svc.cluster.local -
{
  "authority": "httpbin:8000",
  "bytes_received": "0",
  "bytes_sent": "19",
  "connection_termination_details": "-",
  "duration": "0",
  "forwarded_for": "-",
  "method": "GET",
  "protocol": "HTTP/1.1",
  "request_id": "07541777-6ee2-908f-a78b-867fe257ac80",
  "response_flags": "-",
  "status_code": "403",
  "tcp_service_time": "-",
  "timestamp": "2020-10-29T03:25:20.162Z",
  "upstream_service": "-",
  "upstream_cluster": "-",
  "upstream_local": "-",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:60898",
  "requested_server": "outbound_.8000_._.httpbin.foo.svc.cluster.local",
  "response_code_details": "rbac_access_denied_matched_policy[none]",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "uri_path": "/headers",
  "user_agent": "curl/7.73.0-DEV",
  "original_message": "[2020-10-29T03:25:20.162Z] \"GET /headers HTTP/1.1\" 403 - rbac_access_denied_matched_policy[none] - \"-\" 0 19 0 - \"-\" \"curl/7.73.0-DEV\" \"07541777-6ee2-908f-a78b-867fe257ac80\" \"httpbin:8000\" \"-\" - - 172.17.0.7:80 172.17.0.6:60898 outbound_.8000_._.httpbin.foo.svc.cluster.local -"
}

[2020-10-29T03:26:11.561Z] "GET /headers HTTP/1.1" 403 - rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]] - "-" 0 19 0 - "-" "curl/7.73.0-DEV" "090a1897-d696-99b1-90f0-2673113ba258" "httpbin:8000" "-" - - 172.17.0.7:80 172.17.0.6:33204 outbound_.8000_._.httpbin.foo.svc.cluster.local -
{
  "authority": "httpbin:8000",
  "bytes_received": "0",
  "bytes_sent": "19",
  "connection_termination_details": "-",
  "duration": "0",
  "forwarded_for": "-",
  "method": "GET",
  "protocol": "HTTP/1.1",
  "request_id": "090a1897-d696-99b1-90f0-2673113ba258",
  "response_flags": "-",
  "status_code": "403",
  "tcp_service_time": "-",
  "timestamp": "2020-10-29T03:26:11.561Z",
  "upstream_service": "-",
  "upstream_cluster": "-",
  "upstream_local": "-",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:33204",
  "requested_server": "outbound_.8000_._.httpbin.foo.svc.cluster.local",
  "response_code_details": "rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]]",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "uri_path": "/headers",
  "user_agent": "curl/7.73.0-DEV",
  "original_message": "[2020-10-29T03:26:11.561Z] \"GET /headers HTTP/1.1\" 403 - rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]] - \"-\" 0 19 0 - \"-\" \"curl/7.73.0-DEV\" \"090a1897-d696-99b1-90f0-2673113ba258\" \"httpbin:8000\" \"-\" - - 172.17.0.7:80 172.17.0.6:33204 outbound_.8000_._.httpbin.foo.svc.cluster.local -"
}

[2020-10-29T03:28:26.690Z] "- - -" 0 - - rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]] "-" 761 701 5 - "-" "-" "-" "-" "127.0.0.1:80" inbound|8000|| 127.0.0.1:55464 172.17.0.7:80 172.17.0.6:34574 outbound_.8000_._.httpbin.foo.svc.cluster.local -
{
  "authority": "-",
  "bytes_received": "761",
  "bytes_sent": "701",
  "connection_termination_details": "rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]]",
  "duration": "5",
  "forwarded_for": "-",
  "method": "-",
  "protocol": "-",
  "request_id": "-",
  "response_flags": "-",
  "status_code": "0",
  "tcp_service_time": "-",
  "timestamp": "2020-10-29T03:28:26.690Z",
  "upstream_service": "127.0.0.1:80",
  "upstream_cluster": "inbound|8000||",
  "upstream_local": "127.0.0.1:55464",
  "downstream_local": "172.17.0.7:80",
  "downstream_remote": "172.17.0.6:34574",
  "requested_server": "outbound_.8000_._.httpbin.foo.svc.cluster.local",
  "response_code_details": "-",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "user_agent": "-",
  "original_message": "[2020-10-29T03:28:26.690Z] \"- - -\" 0 - - rbac_access_denied_matched_policy[ns[foo]-policy[httpbin]-rule[0]] \"-\" 761 701 5 - \"-\" \"-\" \"-\" \"-\" \"127.0.0.1:80\" inbound|8000|| 127.0.0.1:55464 172.17.0.7:80 172.17.0.6:34574 outbound_.8000_._.httpbin.foo.svc.cluster.local -"
}

```

### CODE REVIEW

**Comment by GregHanson** [comment]
@kushthedude I'm assuming the `goreleaser` test is failing since the `commit_author` (me in this case), does not match the `github:owner` field in `goreleaser.yml `?

**Comment by GregHanson** [comment]
@nitishm is this a change you are interested in pulling in?  Another option is to add new fields to the `AccessLog` struct and then add a command line arg to take in a user specified format string - rather than relying on hardcoded default istio /envoy access log formats which are subject to change

**Comment by kushthedude** [comment]
@GregHanson yes, the failed check is due to the owner issues which can be safely ignored in case of a pull request.

**Comment by nitishm** [comment]
@GregHanson Thanks for the PR. Looks good to me!

**Pull request merged**
